[IG]
ig = fsh-generated/resources/ImplementationGuide-hl7.at.fhir.prenudge.appdata.r4.json
# TODO: use 1.0.0 until build fixed for hl7.at.fhir.template#current
template = hl7.at.fhir.template#1.0.0
# template = https://github.com/HL7Austria/at-fhir-ig-template#current