name: 'PreNUDGE: FHIR IG Review'
description: Submit a review on this IG
title: ''
labels: []
body:
  - type: input
    id: page
    attributes:
      label: Page
      description: Page the comment refers to (e.g. workflow.html).
    validations:
      required: true
  - type: input
    id: line-anchor
    attributes:
      label: Line / Anchor
      description: Line number or anchor the comment refers to (e.g. #app-pairing).
    validations:
      required: false
  - type: input
    id: element
    attributes:
      label: Element
      description: Element the comment refers to (e.g. PreNUDGE IAM).
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the comment.
    validations:
      required: true
  - type: textarea
    id: proposed-change
    attributes:
      label: Proposed Change
      description: The change you suggest.
    validations:
      required: false
  - type: textarea
    id: rationale
    attributes:
      label: Rationale / Comment / Question
      description: Rationale, comment, or question providing further context.
    validations:
      required: false
  - type: dropdown
    id: assessment
    attributes:
      label: Assessment
      description: Assessment of this comment.
      options:
        - '(NEG-S) Negative, severe'
        - '(NEG-G) Negative, minor'
        - '(Z-K) Agree with comment'
        - '(Z-V) Agree with suggestion'
        - '(Z-T) Agree - typo'
        - '(Z-F) Agree with question'
        - '(K) Comment'
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the comment here.
    validations:
      required: false
